{
 "title": "Puppet Stats",
 "time": { "from": "2022-12-01T12:39:55.426Z", "to": "2022-12-02T11:51:08.004Z" },
 "panels": [
  { "title": "Reboot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of servers pending reboot",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "query": "SELECT * FROM reboot" }
   ]
  },
  {
   "title": "Evolution of Servers pending reboot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 1 },
   "targets": [
    { "query": "SELECT * FROM reboot" }
   ]
  },
  { "title": "Security Updates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Available Security Updates - Radar Graph",
   "type": "snuids-radar-panel",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 10 },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "measurement": "security_updates",
     "query": "SELECT * FROM security_updates",
     "select": [
      [
       { "params": [ "ackerman3.upc.es" ], "type": "field" }
      ]
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Mean Evolution | Available Security Updates",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 10 },
   "targets": [
    { "query": "SELECT * FROM security_updates" }
   ]
  },
  {
   "title": "Available Security Updates - Histogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "updates" } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "query": "SELECT LAST(*) FROM security_updates",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Max | Available Security Updates",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "query": "SELECT * FROM security_updates" }
   ]
  },
  {
   "title": "StdDev | Available Security Updates",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "query": "SELECT * FROM security_updates" }
   ]
  },
  { "title": "ESM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Servers with ESM enabled",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "query": "SELECT * FROM esm" }
   ]
  },
  {
   "title": "Evolution of Installed ESM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    { "query": "SELECT * FROM esm" }
   ]
  },
  {
   "title": "Total number of servers running Ubuntu",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "limit": "2",
     "measurement": "os",
     "select": [
      [
       { "params": [ "Ubuntu 14" ], "type": "field" }
      ]
     ]
    },
    {
     "limit": "2",
     "measurement": "os",
     "select": [
      [
       { "params": [ "Ubuntu 16" ], "type": "field" }
      ]
     ]
    },
    {
     "limit": "2",
     "measurement": "os",
     "select": [
      [
       { "params": [ "Ubuntu 20" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Operating System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "UPC - Stats",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "os",
     "query": "SELECT * FROM \"os\" WHERE (\"location\" = 'UPC')",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "UPC" }
     ]
    }
   ]
  },
  {
   "title": "Tauli - Stats",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "os",
     "query": "SELECT * FROM \"os\" WHERE (\"location\" = 'Tauli')",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "Tauli" }
     ]
    }
   ]
  },
  {
   "title": "UPC - Time series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "measurement": "os",
     "query": "SELECT * FROM \"os\" WHERE (\"location\" = 'UPC')",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "UPC" }
     ]
    }
   ]
  },
  {
   "title": "Tauli - Time series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "measurement": "os",
     "query": "SELECT * FROM \"os\" WHERE (\"location\" = 'Tauli')",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "Tauli" }
     ]
    }
   ]
  },
  {
   "title": "UPC - Pie chart",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "os",
     "query": "SELECT * FROM \"os\" WHERE (\"location\" = 'UPC')",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "UPC" }
     ]
    }
   ]
  },
  {
   "title": "Tauli - Pie chart",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "os",
     "query": "SELECT * FROM \"os\" WHERE (\"location\" = 'Tauli')",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "Tauli" }
     ]
    }
   ]
  }
 ]
}