{
 "title": "Service Operation",
 "description": "PuppetStats data for Service Operation (SO) group.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Reboot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of servers pending reboot",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT * FROM reboot WHERE (\"group\" = 'UPCnet/SO')"
    }
   ]
  },
  {
   "title": "Evolution of Servers pending reboot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 1 },
   "targets": [
    {
     "query": "SELECT * FROM reboot WHERE (\"group\" = 'UPCnet/SO')"
    }
   ]
  },
  { "title": "Security Updates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Available Security Updates - Radar Graph",
   "type": "snuids-radar-panel",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 10 },
   "targets": [
    {
     "query": "SELECT * FROM security WHERE (\"group\" = 'UPCnet/SO')"
    }
   ]
  },
  {
   "title": "Mean Evolution | Available Security Updates",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 10 },
   "targets": [
    {
     "query": "SELECT * FROM security WHERE (\"group\" = 'UPCnet/SO')"
    }
   ]
  },
  {
   "title": "Available Security Updates - Histogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "updates" } },
   "targets": [
    {
     "query": "SELECT LAST(*) FROM security WHERE (\"group\" = 'UPCnet/SO')"
    }
   ]
  },
  {
   "title": "Max | Available Security Updates",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT * FROM security WHERE (\"group\" = 'UPCnet/SO')"
    }
   ]
  },
  {
   "title": "StdDev | Available Security Updates",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT * FROM security WHERE (\"group\" = 'UPCnet/SO')"
    }
   ]
  },
  { "title": "ESM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Servers with ESM enabled",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Evolution of Installed ESM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total number of servers running Ubuntu",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"Ubuntu 14\" FROM \"os\" WHERE (\"group\" = 'UPCnet/SO') and (\"location\" = 'UPC') ORDER BY time"
    },
    {
     "query": "SELECT \"Ubuntu 16\" FROM \"os\" WHERE (\"group\" = 'UPCnet/SO') and (\"location\" = 'UPC') ORDER BY time"
    },
    {
     "query": "SELECT \"Ubuntu 20\" FROM \"os\" WHERE (\"group\" = 'UPCnet/SO') and (\"location\" = 'UPC') ORDER BY time"
    }
   ]
  },
  { "title": "Operating System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "UPC - Stats",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT * FROM \"os\" WHERE (\"group\" = 'UPCnet/SO') and (\"location\" = 'UPC')"
    }
   ]
  },
  {
   "title": "Tauli - Stats",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT * FROM \"os\" WHERE (\"location\" = 'Tauli')"
    }
   ]
  },
  {
   "title": "UPC - Time series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "query": "SELECT * FROM \"os\" WHERE (\"group\" = 'UPCnet/SO') and (\"location\" = 'UPC')"
    }
   ]
  },
  {
   "title": "Tauli - Time series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "query": "SELECT * FROM \"os\" WHERE (\"location\" = 'Tauli')"
    }
   ]
  },
  {
   "title": "UPC - Pie chart",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT * FROM \"os\" WHERE (\"group\" = 'UPCnet/SO') and (\"location\" = 'UPC')"
    }
   ]
  },
  {
   "title": "Tauli - Pie chart",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT * FROM \"os\" WHERE (\"location\" = 'Tauli')"
    }
   ]
  }
 ]
}